name: torchsurv-codeqc

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        miniconda-version: "latest"
        python-version: ${{ matrix.python-version }}
        environment-file: dev/environment.yml
        activate-environment: torchsurv
        use-only-tar-bz2: true

    - name: Cache Conda
      uses: actions/cache@v3
      env:
        # This hashFiles function returns a hash value that changes when the environment.yml file changes
        CACHE_NUMBER: ${{ hashFiles('dev/environment.yml') }}
      with:
        path: ~/miniconda3/envs/torchsurv
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Code QC
      shell: bash -l {0}
      run: |
        conda activate torchsurv
        ./dev/codeqc.sh
 
    - name: Tests
      shell: bash -l {0}
      run: |
        conda activate torchsurv
        ./dev/run-doctests.sh
        ./dev/run-unittests.sh